package com.guofeng.personnelblog;

import lombok.extern.slf4j.Slf4j;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

/**
 * @author guofeng
 */
@Slf4j
@MapperScan("com.guofeng.personnelblog.dao")
@SpringBootApplication
public class PersonnelBlogApplication {

    public static void main(String[] args) {
        SpringApplication.run(PersonnelBlogApplication.class, args);
        log.info("运行成功");
        log.info("前台登录http://localhost:8080/");
        log.info("后台登录http://localhost:8080/admin/login");
        log.info("管理员账号admin密码123456");
    }

}
